### ISSUE TITLE
Latest update crashes wordpress

### ISSUE THREAD

**Issue by locutius** [wp-statistics/wp-statistics#173]
After the latest update I find the following errors in the httpd logs:

[Thu Nov 15 11:12:56.646672 2018] [:error] [pid 1768] [client x.x.x.x:30602\
] PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identif\
ier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/blog.brega\
nasher.com/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-\
rest.php on line 27
[Thu Nov 15 11:13:37.476685 2018] [:error] [pid 1718] [client x.x.x.x:57042\
] PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identif\
ier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/blog.brega\
nasher.com/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-\
rest.php on line 27

**Comment by mostafasoufi** [comment]
Thank you for reporting, the problem fixed in this commit. https://github.com/wp-statistics/wp-statistics/commit/cf96d1008e70e56f5e012bcb8810ccf5fb754e6c

Please get [this file](https://raw.githubusercontent.com/wp-statistics/wp-statistics/cf96d1008e70e56f5e012bcb8810ccf5fb754e6c/includes/classes/class-wp-statistics-rest.php) and replace in your WordPress

**Comment by windscreenwiper** [comment]
I just ran the update, 2 minutes ago and got this:  Plugin could not be activated because it triggered a fatal error. Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/marbella/public_html/blog/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-tinymce.php on line 14

**Comment by locutius** [comment]
With the new file wordpress didn't crash but when I went to activate the plugin I received the following error:

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/xxxxxxxxxxxxxxx.com/wp-content/plugins/wp-statistics/includes/classes/class-wp-statistics-rest.php on line 38

**Comment by mostafasoufi** [comment]
The problem solved in the beta version
https://github.com/wp-statistics/wp-statistics/archive/development.zip

The new version will be released soon.

Thanks for reporting.

**Comment by locutius** [comment]
Thank you mostafasoufi.  I can confirm that the beta version seemed to install fine.

**Comment by mostafasoufi** [comment]
Thank you for your test. the new version (12.5.2) will be released soon.

**Comment by mostafasoufi** [comment]
@locutius 
Please consider you should rename `wp-statistics-development` folder to `wp-statistics`

**Comment by locutius** [comment]
Yep. Already did it.  That's why it worked.  Thanks.
