### ISSUE TITLE
&amp on blog name from email

### ISSUE THREAD

**Issue by yusha** [wp-statistics/wp-statistics#249]
Hi, I am on the latest version of the plugin 12.6.2  Whenever I am receiving e-mail notification about stats updates I am having &amp on E-mail name not on subject. Because my blog name or title contains &, for example: My Blog & Co. Please see the screenshot attached for reference. 

<img width="614" alt="bname" src="https://user-images.githubusercontent.com/473559/55196357-c4200600-5174-11e9-8a77-407e70dc5882.png">

**Comment by mehrshaddarzi** [comment]
@yusha @mostafasoufi 

by default WordPress wp_mail function used htmlentities function to Convert Special character in subject.Because some servers know it as spam.
you can use bottom code in function.php : 

```php
add_filter('wp_mail', 'email_subject_remove_sitename');
function email_subject_remove_sitename($email) {
  $blogname = wp_specialchars_decode(get_option('blogname'), ENT_QUOTES);
  $email['subject'] = str_replace("[".$blogname."] - ", "", $email['subject']);    
  $email['subject'] = str_replace("[".$blogname."]", "", $email['subject']);
  return $email;
}
```

more information : 
https://bucketpress.com/converts-html-entities-to-characters
https://stackoverflow.com/questions/20806154/php-mail-special-characters-in-subject-field
https://developer.wordpress.org/reference/functions/wp_mail/
https://wordpress.stackexchange.com/questions/116284/wp-mail-remove-sitename-from-email-subject
