### ISSUE TITLE
Changes to GeoLite2 license and distribution require changes to how you download databases

### ISSUE THREAD

**Issue by 2shortplanks** [wp-statistics/wp-statistics#308]
Currently the [code](https://github.com/wp-statistics/wp-statistics/blob/2156039c02baca3e42cc4246ee18510fe7d22718/includes/classes/class-wp-statistics-updates.php#L11) in class-wp-statistics-updates.php directly downloads databases from a URL at MaxMind.  After December 30th, 2019 this will no longer continue to work.

Due to upcoming data privacy regulations, MaxMind are making significant changes to how users access free MaxMind GeoLite2 databases starting December 30, 2019. The databases will continue to be available without charge and for redistribution. However, you will be required to create an account and use a license key to download the databases, and agree to a new EULA that addresses applicable data privacy regulations.

Learn more on the MaxMind blog: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/.

Mark Fowler
MaxMind

**Comment by mostafasoufi** [comment]
Hi @2shortplanks, 

Are you sure the sign-up form it works? because I getting below error while register for a new account:

> Sorry, we are not able to provide you with an account.

**Comment by itsTheFae** [comment]
The service sign up does indeed work.  You may want to try it again.  

The proper way to address this issue is to add functionality to the Externals settings page that requires each user of WP-Statistics to input their own license key information in order to enable the downloads.   
Using a default or fall-back to redistributed data files does not seem like an ideal situation.  Better to notify admin that they should go to MaxMind and get the database files from their source.  

The new database download links will look something like this: 
`https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_LICENSE_KEY&suffix=tar.gz` 
where `YOUR_LICENSE_KEY` is replaced with the per-user license key.

More information can be found through this page:  
https://dev.maxmind.com/geoip/geoipupdate/

**Comment by mostafasoufi** [comment]
Hi @itsTheFae, The problem solved, we desided to update the DBs manually because there is some limitation in the maxmind for huge traffic.

Best

**Comment by itsTheFae** [comment]
The changes made to address this issue are not the correct solution...
