### ISSUE TITLE
wp-statistics 13.0 locks complete site when bcmath is not installed

### ISSUE THREAD

**Issue by flberger** [wp-statistics/wp-statistics#331]
wp-statistics <= 12.6.13 did not require the bcmath PHP module and works fine without it.

When upgrading to wp-statistics 13.0 without having bcmath installed , the whole Wordpress site becomes inaccessible, including the admin dashboard. The site instead displays

> Composer detected issues in your platform: Your Composer dependencies require the following PHP extensions to be installed: bcmath

This is especially critical when users without shell/file access activate auto updates on such a system. The plugin then updates to 13.0 , and the whole site breaks, leaving these users no way to repair or undo the problem.

_Actual behaviour:_ the site becomes completely inaccessible.

_Expected behaviour:_ the site should continue working, including the admin area. The plugin should display an error for functionality where bcmath is required.

Steps to reproduce:

- Install PHP without bcmath
- Install wp-statistics 13.0
- load the site

**Comment by TheNikkoMan** [comment]
Can confirm, exact thing happened. This sort of thing shouldn't happen.

**Comment by mostafasoufi** [comment]
Hey,

Thank you for reporting the issue and sorry for that, It seems the `platform-check` flag was enabled globally in one of our local-machine and caused the issue, now the issue has been fixed in the commit https://github.com/wp-statistics/wp-statistics/commit/056d4850cc705ebc0f220eca33cfa39ead871431

We're going to release the new version, but before that, could you please let us know that version works fine on your WordPress?

**Comment by flberger** [comment]
I can confirm that commit 056d485 no longer locks the site. The plugin seems usable so far, even without the bcmath module.

**Comment by mostafasoufi** [comment]
Thanks! I'm going to release new version tonight.
