### ISSUE TITLE
WP Statistics doesn't work on my blog

### ISSUE THREAD

**Issue by GiovanniDicanio** [wp-statistics/wp-statistics#349]
The latest version of WP Statistics doesn't show any stat on [my blog](https://blogs.msmvps.com/gdicanio/).
I have attached a screenshot below.

The [blog administrator ](mailto:barb@NOSPAMbarbbowman.net) wrote to me that this is a bug of your plugin (not a fault of the hosting MSMVPS platform).

I'd appreciate if you could fix that bug that makes this plugin unusable.

Thanks.

![image](https://user-images.githubusercontent.com/4692631/107411844-50d8d080-6b0f-11eb-8734-6cd61f186aaa.png)

**Comment by mostafasoufi** [comment]
Hi, thank you for opening the issue, did you check the error logs? it would be useful if you enable the **WP_DEBUG** and see current errors.

**Comment by GiovanniDicanio** [comment]
Hi, thanks for your quick reply. Unfortunately, I'm not the administrator of that web site. Please contact the [blog administrator](mailto:barb@NOSPAMbarbbowman.net) for more details and settings.

**Comment by GiovanniDicanio** [comment]
If it may be of some help, the SQL and PHP versions are as follow:

SQL 568 
PHP v 7.3.13

Thank you.

**Comment by sam-ams** [comment]
Hello, I have the same problem. The graphs are not visible. The WP_DEBUG trace shows the following:

[23-Jun-2022 18:59:08 UTC] PHP Deprecated:  sanitize_url ist seit Version 2.8.0 <strong>veraltet</strong>! Benutze stattdessen esc_url_raw(). in /volume1/web_packages/wordpress/wp-includes/functions.php on line 5211
[23-Jun-2022 18:59:08 UTC] PHP Deprecated:  sanitize_url ist seit Version 2.8.0 <strong>veraltet</strong>! Benutze stattdessen esc_url_raw(). in /volume1/web_packages/wordpress/wp-includes/functions.php on line 5211
[23-Jun-2022 18:59:08 UTC] PHP Deprecated:  sanitize_url ist seit Version 2.8.0 <strong>veraltet</strong>! Benutze stattdessen esc_url_raw(). in /volume1/web_packages/wordpress/wp-includes/functions.php on line 5211

Could that be fixed in the next release?

I am using WP an a Synology NAS. 
WordPress 5.8.3
Server: Apache/2.4.51 (Unix)
PHP: v7.4.28
MYSQL: v10.3.32-MariaDB

**Comment by mostafasoufi** [comment]
Actually, this is not related to the WP-Statistics, can you please take a screenshot of your **Inspect > Console** on your Browser?

**Comment by sam-ams** [comment]
Here is a screenshot of the Console:

<img width="1374" alt="Bildschirmfoto 2022-06-27 um 06 22 54" src="https://user-images.githubusercontent.com/36484012/175860015-02a55ab3-8c4b-4f43-b890-e37923a7ec95.png">

**Comment by mostafasoufi** [comment]
@sam-ams  Seems It's a cors issue, please take a look at [this article](https://crunchify.com/how-to-fix-access-control-allow-origin-issue-for-your-https-enabled-wordpress-site-and-maxcdn/).

**Comment by sam-ams** [comment]
I will try the https migration at the weekend. Will respond after it! Thank you for the analysis / hint! :)

Mit freundlichen Grüßen,
Familie Schulz
________________________________
Von: Mostafa Soufi ***@***.***>
Gesendet: Monday, June 27, 2022 1:48:53 PM
An: wp-statistics/wp-statistics ***@***.***>
Cc: sam-ams ***@***.***>; Mention ***@***.***>
Betreff: Re: [wp-statistics/wp-statistics] WP Statistics doesn't work on my blog (#349)


@sam-ams<https://github.com/sam-ams> Seems It's a cors issue, please take a look at this article<https://crunchify.com/how-to-fix-access-control-allow-origin-issue-for-your-https-enabled-wordpress-site-and-maxcdn/>.

**Comment by mostafasoufi** [comment]
I'll close this issue as it is quite old, and the problem has most likely been resolved due to the recent changes made here.

Best
