### ISSUE TITLE
Programmatically call hit API

### ISSUE THREAD

**Issue by hatsumatsu** [wp-statistics/wp-statistics#396]
What would be the most straight-forward way to track page views with WP Statistics when the site uses AJAX navigation like [barba.js](https://barba.js.org/)? In this scenario each subsequent navigation fetches the pages via AJAX instead of using a native page load so the plugin's JS won't trigger.

I understand that there is an API endpoint `/wp-json/wp-statistics/v2/hit` but it appears that a nonce is needed and all visitor info needs to be transmitted manually. 

Is there a way to just call the `hit` via endpoint fetch/AJAX and let the plugin figure out the visitor's info based on the submitted headers or similar?

**Comment by mostafasoufi** [comment]
Programmatically for most of the visitor's information, it can be, but not entirely sure for some special parameters such as exclusion, page id, etc

Overall this would be a good idea since the plugin doesn't need to print out the visitor's information on the source anymore, I'd personally like the idea and appreciate it!

But the thing is that this needs to be done and other is no quick code to do that. I'll make a plan to work on this for the next releases.

**Comment by hatsumatsu** [comment]
Just curious, is there a roadmap / ETA for this feature? 
An API like this could turn this plugin into THE privacy-friendly analytics solution for headless WP setups :-)

**Comment by mostafasoufi** [comment]
Good to hear you again!

I started reducing passing manual parameters for the endpoint in this commit https://github.com/wp-statistics/wp-statistics/commit/965545af177ccc68d6b133e03d4ad8ddcc5db1f9 
 but still, some of them should be sent manually since could not be fetched dynamically.

Since we're rethinking a JS-based request like GA and also making the plugin more privacy-friendly, this probably fixes the issues, but let's see.

Any idea? let's discuss

**Comment by hatsumatsu** [comment]
@mostafasoufi Thanks for getting back on this! If I understand the commit correctly, the required params to call the hit REST API endpoint are `track_all`, `page_uri`, `_wpnonce`. Is there a documentation on these parameters, especially `track_all`?

Also I guess since the nonce is still required, there is currently no way to use the API in a headless setup where we can't generate a nonce on the frontend, right? I'm wondering if omitting the nonce could be an option since other WP core endpoints don't secure the API like this afaik.

**Comment by mostafasoufi** [comment]
> Is there a documentation on these parameters, especially track_all?

Actually, there are more, I mentioned the other ones in [this topic](https://wordpress.org/support/topic/wp-statistics-does-not-work-with-a-cache/#post-16131658) which is related to this issue. but will create the document for this endpoint soon!

In the case of the generating nonce, you can generate it by `wp_create_nonce('wp_rest')` and for the other ones, you can get them by `\WP_STATISTICS\Helper::getHitsDefaultParams()` in frontend.

**Comment by mostafasoufi** [comment]
The below parameters are removed as well:

– _wpnonce
– page_uri
– time
– referred

– https://github.com/wp-statistics/wp-statistics/commit/a474f62b39cf6588283fe3a54af359eb646532eb
– https://github.com/wp-statistics/wp-statistics/commit/01a17d9375f1ce3fbf7b690a47b16e188c8f82d9

So, I guess we can close the issue since most of the parameters are removed from the front-end.

Thank you!
