### ISSUE TITLE
Error message: plugin settings

### ISSUE THREAD

**Issue by CBDesign3** [wp-statistics/wp-statistics#405]
This has been popping up on every backend page for every client I have this plugin installed:
Here is an error associated with Connecting WordPress Rest API
Please Flushing rewrite rules or activate WordPress REST API for performance WP-Statistics Plugin Cache / Go [Settings->Permalinks](https://www.cbgraphicdesigns.com/design/wp-admin/options-permalink.php)

Following the instructions doesn't delete this. Please advise.
I just read the WP API... issue comments and I see that you are going to fix this on your next update. I've had a lot of concerned clients with this popping up.
Thanks.

**Comment by mostafasoufi** [comment]
Thank you for opening the issue, this is quite strange, anyway, can you please give one URL of the website that has the issue? we need to double check the rest API endpoints.

**Comment by mostafasoufi** [comment]
Seems the issue is related to the Apache **Mod_Security**, so please ask your host service provider to disable it.

<img width="1384" alt="Screen Shot 2022-07-21 at 5 01 37 PM" src="https://user-images.githubusercontent.com/701520/180214095-b5d74208-2bfd-4205-afeb-01c6b951374d.png">

Also, you can disable it yourself by .htaccess

https://ubiq.co/tech-blog/how-to-disable-mod_security-in-apache-using-htaccess/
