### ISSUE TITLE
Report security issues!

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#446]
Hi Team
I recently noticed that your plugin saves the list of all site users along with their username and ID - primary key in local storage!! (which is accessible to everyone)
This happens when you enter this page and click on the filter
**/wp-admin/admin.php?page=wps_visitors_page
![Screenshot 2024-01-03 133608](https://github.com/wp-statistics/wp-statistics/assets/61265957/4870c44f-85d8-410c-a84c-044b7fd0d8d4)

As you know better than me, this information can be misused in various ways, especially by using techniques such as Cross-Site Scripting (XSS).
Thank you for checking and replacing the safer way for this issue

Local Storage Name :
wp-statistics-visitors-filter

in directory:
wp-statistics/assets/dev/javascript/pages/visitors.js

BR

**Comment by Sinapars** [comment]
Hi Again @mostafasoufi ,
Thanks For Response 
I have sent you complete information from the name of the local storage name (**wp-statistics-visitors-filter**) that is specific to your plugin to the path of the file in which this logic is written (**wp-statistics/assets/dev/javascript/pages/visitors.js**), as well as how to reproduce this problem:

> This happens when you enter this page and click on the filter
**/wp-admin/admin.php?page=wps_visitors_page

If you check these steps, you can easily see or reproduce the problem
BR

**Comment by mostafasoufi** [comment]
It appears your browser is logging the contents of [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to a file. This may be due to an extension or setting in your browser. I recommend disabling any extensions or changing any settings that could be causing this behavior.

In addition, I noticed that some unencrypted data was being stored in local storage. This data should be encrypted to protect user privacy. To address this, I have removed the ability to save filter data to local storage. This will improve both user privacy and performance by reducing the amount of data stored on the browser.

Thanks!

**Comment by mostafasoufi** [comment]
Actually, there's no need to manually remove the local storage as it is set to automatically delete after 3 hours. It is unusual that your browser logged that on the disk, but rest assured, we will address this in the next version of the software.

Thank you for bringing this to our attention!
