### ISSUE TITLE
Question: The logic of checking online users in the WP Statistics Plugin

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#505]
Hi Team,
First question:
In the latest version (14.8.1), the number of online users is unusually higher than before, for example, in the previous versions, this number was about 70 people, but in the latest version, it has reached about 250 people.
Has the logic of checking online users changed?

Second question:
According to the review I had in the browser network tab, the number of online users is calculated every minute, but in the plugin settings, there is an option to change this time, but I think that changing it has no effect on the duration of checking online users!

![image](https://github.com/wp-statistics/wp-statistics/assets/61265957/dca7fa16-b61c-4d14-98b6-41a62365cdc5)

BR

**Comment by amirfallahii** [comment]
Hi @Sinapars 

Thank you for reporting this issue.

Please let us know whether the options "Bypass Ad Blockers" and "Cache Compatibility Mode" in Settings - Basic Tracking are enabled or disabled?

We appreciate your cooperation.
Regards,

**Comment by Sinapars** [comment]
Both of these options are disabled.

FYI:
I don't use any cache plugins.
My website is in an internal network and cannot be accessed from the outside (internet network) and the users are clearly defined and there are no robots.

BR

**Comment by amirfallahii** [comment]
Hi @Sinapars 

The issue has been resolved in version 14.9.3. Please update the plugin to this version, and it should fix the problem. 

Thank you for bringing this to our attention and for your patience.
Regards,

**Comment by Sinapars** [comment]
Hi Again Team,

I previously reported this issue, but I'm experiencing it again after upgrading from an older version of WP Statistics to the latest release.

After the upgrade, the number of online users dropped significantly. In the older version, I usually saw around 70–80 online users, but now the count is typically around 10.

I don't have any caching plugins installed, and I have already verified that the plugin settings are configured correctly.

Has there been any change in the logic used to calculate or detect online users in recent versions? If so, could you please provide more details about what changed and how it might affect the reported online user count?
@amirfallahii 
@mostafasoufi 

Thank you.

**Comment by mostafasoufi** [comment]
Hi @Sinapars,

Thanks for the detailed follow-up, and yes, the logic changed. Here is what is going on.

In the v14 rewrite we removed the old real-time `useronline` table. The online count is now taken from the main visitor table: distinct visitors (today) whose last activity (`last_view`) is within the last 5 minutes. Tracking is hit-based (page load and navigation), with no background heartbeat, so a visitor only stays "online" while they keep loading or navigating pages.

That is why your count is lower: on an internal site where users open a page and stay on it without navigating, `last_view` stops updating and they drop out of the 5-minute window after a few minutes, even with the tab open. The old table kept those idle sessions counted. So the new number is a stricter "active in the last ~5 minutes" measure, not lost data.

On the interval setting: that controls the real-time view's refresh rate (the request you see about every minute), not the 5-minute detection window, which is currently fixed in code. That matches what you saw. If a configurable window would help you, I can add a setting or filter for it.

By the way, v15 is a big one: we have essentially rebuilt WP Statistics from the ground up, with a fully restructured architecture and data layer focused on performance and accuracy. Given how well you know the internals, your feedback on an early build would be hugely valuable, so we would be glad to set you up with beta access. And as a thank-you for being such an active, long-time user, we would also like to offer you a lifetime Premium license. Just let me know if either sounds good.

Regards,

**Comment by Sinapars** [comment]
Hi @mostafasoufi Jan,

First of all, thank you for the detailed explanation. That really helped me understand what changed.

Just to make sure I understood correctly: I upgraded from a version that was only about three months old to the latest release, and that’s when I noticed this difference in the online users count. My installation wasn't running a very old version. Based on your explanation, is it correct that this behavior change was already introduced during that period?

Also, I was wondering whether changing the Attribution Model setting would have any impact on this online users calculation, or is it completely unrelated?

And thank you so much for your kindness and generosity.

I'm actually very excited about v15. If I remember correctly, it was almost a year ago when we were discussing this version and its major architectural changes in other topics. Back then, we talked quite a bit about the extensive performance improvements that were planned and how many long-standing efficiency concerns would be addressed in that release.

To be fair, the performance improvements in recent versions have already been very noticeable, but I'm still extremely excited to see what v15 brings. I'll be happy to help in any way I can during testing.

Unfortunately, due to the recent events in Iran and the extended internet disruptions we've experienced, my workload has increased significantly, so I've been a bit away from these discussions lately.

That said, during this time I also noticed that one of your other plugins that I really like, WP SMS, has gone through a rebranding and seems to have some exciting developments ahead. I remember we had many great conversations about it in its repository last year, and even put together a roadmap for it. Recently I saw that you've published a Persian website, changelog, and roadmap for the project as well. I'm genuinely excited to see where that project is heading too.

Regarding the lifetime license and beta testing, what would be the best way to get in touch with you?

Thanks again for everything. I truly appreciate all the work you and the team are doing, and I sincerely hope you continue to grow and shine even more in the WordPress ecosystem. You should be proud of what you've built.

Regards,
Sina

**Comment by mostafasoufi** [comment]
Hi @Sinapars,

Thank you, that is very kind, and good questions.

Timeline: the relevant change is in v14.16, in the changelog as "Improved the online tracking system by removing heartbeat requests." That release moved online detection to the visitor table's last activity and dropped the background ping. So if your previous version was before 14.16, that is the boundary where the behavior changed; if it was already 14.16.x, the logic was the same and any remaining difference comes down to traffic patterns.

Attribution Model: unrelated to the online count. That setting only controls how a visitor's traffic source is credited (first-touch vs last-touch for referrers and campaigns). The online count is based purely on recent activity (`last_view` within the window), so the attribution model has no effect on it.

On v15: you remember correctly, this is where those architecture and performance plans come together, and your feedback during testing would mean a lot. Thanks too for the kind words about WSMS (the rebrand and roadmap are part of a bigger push your past input helped shape). I am sorry about the disruptions you have been dealing with, and I hope things ease soon, no rush on any of this.

For the lifetime Premium license and the v15 beta, the easiest is to email me directly at mostafa@veronalabs.com and I will get you set up.

Thanks again, Sina.

Regards,

**Comment by mostafasoufi** [comment]
Hi Sina,

One more thing about WSMS, since you asked where it is heading. v8.0 is the big one. We are rebuilding it from an SMS plugin into a full messaging platform, on a new modular architecture and a completely restructured admin. The new layout is organized around:

- **Audience:** contacts, tags, and lists, instead of the old flat subscriber list
- **Campaigns and Automation** for building real messaging flows
- **Channels:** gateways, integrations, webhooks, and a messaging button, all in one place
- **Identity:** auth channels, registration forms, profile fields, and templates, so OTP and 2FA become a first-class part of the platform

A lot of this goes back to the roadmap we worked on together last year, so it would mean a lot to have you test an early v8 build too, the same way as WP Statistics v15. If you are up for it, I will set you up on both.

The same email works for all of this: mostafa@veronalabs.com.

Talk soon, and thanks again, Sina.

Regards,
