### ISSUE TITLE
Issue with Displaying Visitors Statistics Before June 1, 2024

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#594]
Hello Team,

It seems that the **Visitors Statistics** for posts and pages from their initial publication up **until June 1, 2024**, are displayed as **zero**. This occurs both in charts and other statistics sections, and it appears that these views are not included in the total statistics either.

![image](https://github.com/user-attachments/assets/d9d9c6fa-2b5d-4407-8995-1e956074630a)

![image](https://github.com/user-attachments/assets/2c0ba145-a446-4bd1-99f6-53f7cfa5ef13)

I’d appreciate it if you could look into this issue. Please let me know if you need any additional details to assist with debugging.

Thanks in advance for your time and support!

BR,
Sina

**Comment by amirfallahii** [comment]
Hello @Sinapars,

Thank you for your message and for sharing your observations. We appreciate your continued support and valuable feedback, which always helps us improve.

In the past, there was an option in the settings called "**Record visited pages**". When enabled, this option allowed the plugin to record detailed data about which pages each visitor viewed. However, if this option was not activated, the plugin only recorded general page view counts, without associating them with individual visitors. A few months ago, we removed this setting entirely, and now the plugin records detailed page visit data for all visitors by default, ensuring accurate insights moving forward.  

Regarding the issues you raised:  

1. **Chart not displaying visitor details before June**: This happens because, in the past, the "Record visited pages" option was not enabled on your site. As a result, we don’t have the necessary data to show how many unique visitors viewed a specific page for those earlier periods. The views data, however, comes from a separate source and is not affected by this.  

2. **Page Insights showing zero visitors**: This issue also stems from the absence of detailed visitor data for the selected date range. Since the feature wasn’t active before, the system cannot calculate unique visitors for that period. However, for any data collected after the setting was removed and detailed tracking became default, the visitor counts will display correctly.  

We hope this clarifies the situation. Please feel free to let us know if you have additional questions or suggestions. Your insights are always invaluable to us!  

Best regards,
