### ISSUE TITLE
"Number of views" does not correspond to the actual number of displayed pages

### ISSUE THREAD

**Issue by LiangYongAI** [wp-statistics/wp-statistics#607]
@mhdizmni ![428da7fca37cf130d8c07d888bd3ef72](https://github.com/user-attachments/assets/8bc12133-d5c3-46c0-ae7d-0bd1e62e4473)
I have noticed that the "Number of views" does not correspond to the actual number of displayed pages. After testing, I found that if there are duplicate pages, the subsequent pages replace the previous ones, and their access times are also overwritten. This seems unreasonable. Is it possible to modify this behavior?

**Comment by Sinapars** [comment]
Hi Team,

I had written and prepared a lot of suggestions for this page:

**First Page:**
`admin.php?page=wps_visitors_page&type=single-visitor&visitor_id=342340`

Like adding filters by date, pagination for reviewing all records, and so on.

But then I noticed that everything I need is already **available** on this page of your plugin, and it’s even more complete and precise:

`admin.php?page=wps_visitors_page&tab=visitors&user_id=762&from=2024-12-10&to=2024-12-10`

Honestly, I feel these two pages **overlap**, and it would be better if they were **merged**. just, the two side box from the first page—which, by the way, contains useful information—could be added to the page I mentioned above.

This is the two box:

![image](https://github.com/user-attachments/assets/445ec3d8-f1e8-4171-8de0-3f777455f71c)

BR,
Sina

**Comment by mhdizmni** [comment]
Hi @LiangYongAI,

Sorry for the delayed response.

The "Recent Views" section shows the latest pages a user has visited, displaying only the most recent visit to each page. For example, if a user views Page A multiple times, only the latest visit will appear.

The "Number of Views", on the other hand, represents the total count of visits. If a user views Page A 10 times, this number will reflect all 10 views, even though only one instance of Page A appears in "Recent Views."

We have planned some changes for this page to show each visit of the same page separately.

Rest assured, we continuously evaluate options and user feedback to enhance WP Statistics.

Regards,
Matthew

**Comment by mhdizmni** [comment]
Dear @Sinapars,

The two pages serve different purposes:
- `?page=wps_visitors_page&type=single-visitor&visitor_id=XXX`: Displays detailed information about a specific visitor.
- `?page=wps_visitors_page&tab=visitors&user_id=XXX`: Serves as a directory of visitors.

It’s important to note that a single visitor may appear multiple times on the Visitor Insights page. This happens when they visit the site on different days or use different devices, IPs, etc. However, the Visitor Report page shows the detailed data for each instance of the visitor.

Regards,
Matthew
