### ISSUE TITLE
 IP query to retrieve the most recent record

### ISSUE THREAD

**Issue by LiangYongAI** [wp-statistics/wp-statistics#617]
![image](https://github.com/user-attachments/assets/0c5475aa-b078-438b-a3e5-742dc7bfed5a)
I have noticed that the same IP address may result in two separate records. However, when querying the IP using the code below to retrieve data, it always returns the older record. 

$visitorModel = new \WP_Statistics\Models\VisitorsModel();
$visitor = $visitorModel->getVisitorData(['ip' => $ip, 'page_info'  => true, 'user_info'  => true]);
    
I have two questions:

１：After how long will visits from the same IP be recorded as two separate entries?

２：How can I modify my IP query to retrieve the most recent record?
@mhdizmni

**Comment by mhdizmni** [comment]
Hi @LiangYongAI,

Visitor instances are recorded daily based on IP addresses. For example, if a user (same IP) visits your site on two consecutive days, two separate visitor instances will be logged.

That being said, I recommend using the `getVisitorsData` method instead of `getVisitorData`. The `getVisitorsData` method retrieves all visitors for a matching IP, which should better suit your needs.

Here is an example:
```
$visitorsModel = new \WP_Statistics\Models\VisitorsModel();
$visitors = $visitorModel->getVisitorsData([
    'ip' => '127.0.0.1',
]);
```

Additionally, we'll update the `getVisitorData` method in an upcoming release to return the most recent visitor, not the oldest. Thank you for bringing this to our attention!

Regards,
Matthew

**Comment by LiangYongAI** [comment]
@mhdizmni 
I found that in getVisitorData() ,It get first view
![image](https://github.com/user-attachments/assets/ecfb4dd9-fac9-49c6-abaa-a3c87d57fa03)
but in getVisitorsData(), it get last view
![image](https://github.com/user-attachments/assets/137f354a-1827-4b0a-a2f3-6beda2270e55)

I want to get first view in getVisitorsData(), can you modify to make the two function to get the same element?

**Comment by mhdizmni** [comment]
I’m locking this conversation as we’ve continued discussing this in a new issue here: #624
